const data = [
  {
    firstName: "John",
    lastName: "Doe",
    branch: "Hispanic",
    status: "FTGRAD",
    registrationNumber: "12345",
    email: "jdoe@example.com",
    attendance: 17.9,
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    branch: "Hispanic",
    status: "TRANSFER",
    registrationNumber: "23456",
    email: "jsmith@example.com",
    attendance: 18.1,
  },
  {
    firstName: "Sarah",
    lastName: "Thomas",
    branch: "Hispanic",
    status: "FTFT",
    registrationNumber: "34567",
    email: "sthomas@example.com",
    attendance: 17.6,
  },
  {
    firstName: "Frank",
    lastName: "Brown",
    branch: "Race/ethnicity unknown",
    status: "FTFT",
    registrationNumber: "45678",
    email: "fbrown@example.com",
    attendance: 19,
  },
  {
    firstName: "Mike",
    lastName: "Davis",
    branch: "White",
    status: "FTFT",
    registrationNumber: "56789",
    email: "mdavis@example.com",
    attendance: 18.2,
  },
  {
    firstName: "Jennifer",
    lastName: "Wilson",
    branch: "Asian",
    status: "TRANSFER",
    registrationNumber: "67890",
    email: "jwilson@example.com",
    attendance: 18.5,
  },
  {
    firstName: "Jessica",
    lastName: "Garcia",
    branch: "White",
    status: "FTFT",
    registrationNumber: "78901",
    email: "jgarcia@example.com",
    attendance: 18.8,
  },
  {
    firstName: "Fred",
    lastName: "Clark",
    branch: "Hispanic",
    status: "FTGRAD",
    registrationNumber: "89012",
    email: "fclark@example.com",
    attendance: 19.2,
  },
  {
    firstName: "Bob",
    lastName: "Lopez",
    branch: "White",
    status: "FTFT",
    registrationNumber: "90123",
    email: "blopez@example.com",
    attendance: 18.5,
  },
];

export default data;
